# Programa Ingenias+ Data Science

Como dijimos en clases anteriores, Python tiene implementadas muchas librerias para poder trabajar con datos. En la clase de hoy trabajaremos con una de ellas: `Numpy`.

Antes de comenzar, vamos a hablar un poco de esta libreria o modulo.

**Numpy** es una librería optimizada para realizar cálculos numéricos con vectores y matrices. A diferencia de otros lenguajes de programación, Python no posee en su estructura central la figura de matrices. Eso quiere decir que para poder trabajar con esta estructura de datos deberiamos trabajar con listas de listas. NumPy introduce el concepto de arrays o matrices.

Al ser de código abierto, `numpy` posee una documentación muy amplia que es **SIEMPRE RECOMENDABLE** consultar.

- [Documentacion NumPy](https://devdocs.io/numpy/)

## Clase 4: Introduccion a NumPy

# Ejercicios


In [56]:
import numpy as np

1. Crear un arreglo de ceros de longitud 12



In [57]:
array1 = np.zeros(12)
print(array1)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


2. Crear un arreglo de longitud 10 con ceros en todas sus posiciones y un 10 en la posición número 5

In [58]:
array2 = np.zeros(9)
array2 = np.insert(array2,4,10)
print(array2)


[ 0.  0.  0.  0. 10.  0.  0.  0.  0.  0.]


3. Crear un arreglo que tenga los números del 10 al 49

In [59]:
array3 = np.arange(10,50)
print(array3)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


4. Crear una arreglo 2d de shape (3, 3) que tenga los números del 0 al 8

In [60]:
num = np.arange(0,9)
array4 = np.array(num).reshape(3,3)
print(array4)

[[0 1 2]
 [3 4 5]
 [6 7 8]]



5. Crear un arreglo de números aleatorios de longitud 100 y obtener su media y varianza

In [61]:
# Se crean números enteros aleatorios entre 100 y 500.
array5 = np.random.randint(100, 500, size=100)

media = np.mean(array5)
varianza = np.var(array5)

print("Media:", media)
print("Varianza:", varianza)

Media: 288.92
Varianza: 13546.3536


6. Calcular la media de un arreglo usando np.sum

In [63]:
#Se usa el array anterior para comparar resultados.
sum = np.sum(array5)
total_elements = array5.size

if total_elements == 0:
  print("No se puede calcular la Media")
else:
  calculated_mean = sum/total_elements
  print("Media:", calculated_mean)

Media: 288.92


7. Calcular la varianza de un arreglo usando np.sum y np.mean

In [65]:
# Calcula de la varianza para datos no agrupados
# media y total_elements se declaran mas arriba
if total_elements == 0:
  print("No se puede calcular la Varianza")
else:
  sum2 = np.sum((array5-media)**2)
  varianza2 = sum2/total_elements
  print("Varianza:", varianza2)


Varianza: 13546.3536


8. Crear un array de números aleatorios usando np.random.randn.

In [67]:
array8 = np.random.randn(2,4)
print(array8)

[[ 0.30297677  0.31726594 -1.75838137  0.81518914]
 [ 1.35125003 -0.81009975  1.68569946 -0.67526323]]
